### ISSUE TITLE
Initialize with custom default categories and cards

### ISSUE THREAD

**Issue by ryanblackmore** [indigane/cardsort#4]
Is there a recommended way to have the page load with default categories and cards? Something like being able to pass a JSON formatted similarly as the Export Result output into the initial page load?

**Comment by indigane** [comment]
Do you mean the creation form, where you create a new card sorting? It is not currently possible to pre-fill that.

For the card sorting page, you can can pass it query parameters as below.

```url
https://indigane.github.io/cardsort/card-sort.html?cards=a,b,c&categories=1,2,3&allowCategoryEditing=0
```

This is currently undocumented, but I can document it if there's demand for it.

If this doesn't answer your question, could you add some details, I'm not sure I understood.

**Comment by ryanblackmore** [comment]
That answers my question. I only saw in the code where it interprets a hash but didn't quite get the query params or how to format them. Thanks!
